@startuml
class Заявление {
- LocalDate ДатаРегистрации
- String НомерРегистрации
- Boolean
- Integer ФактВремяОказанияУслуги
- LocalDate ФактДатаЗавершенияРабот
- Boolean ИсточникЗаявления
- LocalDate РасчетСрок
- Integer Приоритет
}
'Заявление o-- Статус
Заявление o-- ФизЛицо
'Заявление o-- ФизЛицо
Заявление o-- Представитель
Заявление o-- Заявитель
'
'class Статус {
'- String Название
'- Integer Ограничения
'- Integer РазрешениеСоздания
'- Long ЭтапРассмотрения
'}
'
class ФизЛицо {
- String Фамилия
- String Имя
- String Отчество
- String СНИЛС
- LocalDate ДатаРождения
- String ИНН
- String АдресРегистрации
- String ФактАдрес
- String Телефон
- String Почта
- String Пол
}
'
'class ОрганизацияФизЛица {
'- int ТипОрганизации
'- String Должность
'}

'ОрганизацияФизЛица "1" o-- "1" ФизЛицо
'ОрганизацияФизЛица "N" --o "1" Организация

class Представитель {
- int ТипПредставителя
- String Название
- String ИНН
- String АдресРегистрации
- String ФактАдрес
- String Телефон
- String Почта
- String Фамилия
- String Имя
- String Отчество
- String СНИЛС
- LocalDate ДатаРождения
- String ОГРН
- String ПолноеНазвание
- String КПП
}

'Представитель o-- Организация
Представитель o-- ФизЛицо
'Представитель o-- ТипПредставителя

class Заявитель {
- int ТипПредставителя
- String Название
- String ИНН
- String АдресРегистрации
- String ФактАдрес
- String Телефон
- String Почта
- String Фамилия
- String Имя
- String Отчество
- String СНИЛС
- LocalDate ДатаРождения
- String ОГРН
- String ПолноеНазвание
- String КПП
}

'Заявитель o-- Организация
'Заявитель o-- ФизЛицо
'Заявитель o-- ТипПредставителя

'class ТипПредставителя {
'    Long Идентификатор
'    String Наименование
'}
'
'class Организация {
'- String Название
'- String ИНН
'- String ОГРН
'- String АдресРегистрации
'- String ФактАдрес
'- String Телефон
'- String Почта
'- int ТипОрганизации
'}
'
'class Документ {
'- Long ТипСущности
'- CardViewEntity cardView
'- String Номер
'- String Название
'- String Создатель
'- LocalDate ДатаДействия
'- String Описание
'- String ЭлекПодписьИнфо
'- int СтатусЭП
'- boolean ВнешПодпись
'}
'
'class ДокументЗаявление {
'}
'ДокументЗаявление --o Заявление
'ДокументЗаявление --o Документ
'
'Документ "1" o-- "N" ОбъектФайла
'
'class ОбъектФайла {
'- String Название
'- String ПутьКФайлу
'- String Формат
'- int Размер
'- String ХэшФайла
'- boolean Временный
'- boolean Удален
'- Integer НомерПорядка
'- String MIME-тип
'- LocalDateTime ВремяПроверки
'- Long СтатусПроверки
'}
'
'class ИтоговыйДокументЗаявления {
'}
'ИтоговыйДокументЗаявления "1" o-- "1" ДокументЗаявление
'
'class ПричиныОтказаЗаявления {
'- String detail
'- String recommendation
'}
'
'ПричиныОтказаЗаявления o-- Заявление
'ПричиныОтказаЗаявления o-- ПричинаОтказа
''
'class ПричинаОтказа {
'- String КороткоеНазвание
'- String ПолноеНазвание
'- boolean Активно
'- LocalDate АктивноСДаты
'- LocalDate АктивноДоДаты
'}
'
'class ЭтапСтатуса {
'- Long Идентификатор
'- String Название
'}
'
'class ИсторияСтатуса {
'- Long Идентификатор
'- LocalDateTime ДатаИзменения
'}
'
'ИсторияСтатуса --o Заявление
'ИсторияСтатуса --o Статус
'
'class УведомленияПользователя {
'- String Тема
'- String Сообщение
'- boolean Прочитано
'- Integer Категория
'- String Почта
'- LocalDateTime ВремяОтправки
'- String СтатусОтправки
'}
'
'ФизЛицо --o УведомленияПользователя
'УведомленияПользователя o-- Заявление
'
'
'class СтатусУведомления {
'- StatusPathEntity ПереходУведомления
'- Boolean УведомлятьВладельца
'- Boolean УведомлятьЗаявителя
'- Boolean УведомлятьПредставителя
'- Boolean УведомлятьПодписантов
'- String ШаблонСообщения
'- String ШаблонОтправителя
'}
'СтатусУведомления --o УведомленияПользователя
'СтатусУведомления "1" --o "N" ПереходСтатуса
'
'
'class ПереходСтатуса {
'- String Заголовок
'- String Описание
'- StatusEntity ИзСтатуса
'- StatusEntity ВСтатус
'# boolean Завершен
'- Integer Ограничения
'- Integer РазрешениеСоздания
'- String ТекстСкрипта
'- Integer НомерВПорядке
'}
@enduml