@startuml
package api {
  class CauseController {
    + ResponseListDTO<CauseDTO> getAll(Long id, EntityCondition filter,\nSortFields sort, LimitOffset limit)
    + CauseDTO getOne(Long id, Long causeId)
    + CauseDTO create(Long id, Long causeId)
    + CauseDTO update(Long id, Long causeId, CauseDTO dto)
    + void remove(Long id, Long causeId)
  }

  class CauseService {
    + ResponseListDTO<CauseDTO> getAll(Long id, EntityCondition filter,\nSortFields sort, LimitOffset limit)
    + CauseDTO getOne(Long id, Long causeId)
    + CauseDTO create(Long id, Long causeId)
    + CauseDTO update(Long id, Long causeId, CauseDTO dto)
    + void remove(Long id, Long causeId)
  }

  class CauseRepository {
    + Class<CauseEntity> getEntityClass()
  }

  class ServiceService {
  }
}

class infrastructure.DynamicMapper {
  + TView toDto(TEntity entity)
  + TEntity toEntity(TView entity)
  + TEntity toEntity(TEntity entity, TView entity)
}

package dto {
  class CauseDTO {
  - Long id
  - String nameShort
  - String nameFull
  - LocalDate activeFrom
  - LocalDate activeTo
  - Long serviceId
  }
}

package db {
  class CauseEntity {
  - String nameShort
  - String nameFull
  - boolean active
  - LocalDate activeFrom
  - LocalDate activeTo
  - ServiceEntity service
  }

  class ServiceEntity {

  }

  ServiceEntity "1" *-- "*" CauseEntity
}
CauseController --> CauseDTO
CauseController --> CauseService

CauseService --> DynamicMapper
CauseService --> CauseRepository
CauseService --> CauseEntity
CauseService --> ServiceService

CauseRepository --> CauseEntity

DynamicMapper --> CauseEntity
DynamicMapper --> CauseDTO

'interface repositories.AbstractRepository {
'}
'
'CauseRepository --|> AbstractRepository
@enduml