@startuml

class api.ServiceController {
  + ResponseListDTO<ServiceDTO> getAll(EntityCondition filter, SortFields sort)
  + ServiceDTO getService(Long id)
  + ServiceDTO createService(Long id)
  + ServiceDTO updateService(Long id, ServiceDTO dto)
  + void removeService(Long id)
  + void changeServiceState(Long id, int stateId)
}

class api.ServiceService {
  + ResponseListDTO<ServiceDTO> getAll(EntityCondition filter, SortFields sort)
  + ServiceDTO getService(Long id)
  + ServiceDTO createService(Long id)
  + ServiceDTO updateService(Long id, ServiceDTO dto)
  + void removeService(Long id)
  + void changeServiceState(Long id, int stateId)
}

class infrastructure.DynamicMapper {
  + TView toDto(TEntity entity)
  + TEntity toEntity(TView entity)
  + TEntity toEntity(TEntity entity, TView entity)
}

class dto.ServiceDTO {

}

class api.ServiceRepository {
+ Class<ServiceEntity> getEntityClass()
+ List<ServiceEntity> findByNameShort(String)
+ List<ServiceEntity> findByTextSearchOnAllAttr(String)
}

class db.ServiceEntity {
'- String nameFull
'- String nameShort
'- LocalDate activeFrom
'- LocalDate activeTo
'- boolean personEnabled
'- boolean businessmanEnabled
'- boolean companyEnabled
'- String picUrl
'- int state
'- Integer restrictions
'- String serviceCode
'- String scriptText
'- Integer orderNumber
}

ServiceController --> ServiceDTO
ServiceController --> ServiceService

ServiceService --> ServiceDTO
ServiceService --> ServiceRepository
ServiceService --> DynamicMapper

ServiceRepository --> ServiceEntity
ServiceService --> ServiceEntity

DynamicMapper --> ServiceEntity
DynamicMapper --> ServiceDTO
@enduml