@startuml
class api.FileController {
  + void uploadFile(MultipartFile file, Long objectId)
  + void deleteFile(Long fileId, Long objectId)
  + void downloadFile(HttpServletResponse response, Long fileId)
  + List<StoredFileDTO> getAll(Long objectId)
  + StoredFileDTO getById(Long fileId)
}

class api.RequestDocumentController {
  + ResponseListDTO<RequestDocumentDTO> getAll(EntityCondition filter, SortFields sort, LimitOffset limit, String registry, Long statusStage)
  + RequestDocumentDTO getOne(Long id)
  + RequestDocumentDTO create(Long id)
  + RequestDocumentDTO update(Long id, RequestDocumentDTO dto)
  + void remove(Long id)
}
class api.RequestService {

}


class api.RequestDocumentService {
  + ResponseListDTO<RequestDocumentEntity> getAll(EntityCondition filter,\nSortFields sort, LimitOffset limit, String registry, Long statusStage)
  + RequestDocumentEntity getOne(Long id)
  + RequestDocumentEntity create(Long id)
  + RequestDocumentEntity update(Long id, RequestDocumentEntity dto)
  + void remove(Long id)
}

class infrastructure.DynamicMapper {
  + TView toDto(TEntity entity)
  + TEntity toEntity(TView entity)
  + TEntity toEntity(TEntity entity, TView entity)
}

class dto.RequestDocumentDTO {
- Long id
- String cost
- boolean personEnabled
- boolean businessmanEnabled
- boolean companyEnabled
- LocalDate activeFrom
- LocalDate activeTo
}

class dto.FileDTO {
- String id
- String name
- Integer size
- String extension
- Integer orderNumber
- String mimeType
- String comment
}
RequestDocumentDTO "1" *-u- "1" FileDTO


class api.RequestDocumentRepository {
+ Class<ServiceEntity> getEntityClass()
+ List<ServiceEntity> findByNameShort(String)
+ List<ServiceEntity> findByTextSearchOnAllAttr(String)
}

package db {
  class RequestDocumentEntity {

  }

  class DocumentEntity {
  - Long entityTypeId
  - CardViewEntity cardView
  - String num
  - String name
  - String author
  - LocalDate issuanceDate
  - String description
  - List<StoredFileEntity> files
  - String signInfo
  - int signStatus
  - boolean externalSign
  }

  class RequestEntity {

  }

  class ServiceDocumentEntity {
  }

  RequestDocumentEntity --> DocumentEntity
  RequestDocumentEntity <-- RequestEntity
  RequestDocumentEntity --> ServiceDocumentEntity

}
RequestDocumentController --|> FileController

RequestDocumentController -u-> RequestDocumentDTO
RequestDocumentController --> RequestDocumentService
RequestDocumentController -u-> DynamicMapper
RequestDocumentService --> RequestDocumentRepository
RequestDocumentRepository --> RequestDocumentEntity
RequestDocumentService --> RequestDocumentEntity
DynamicMapper --> RequestDocumentEntity
RequestDocumentService --> RequestService

@enduml